image: node:latest

stages:
  - build
  - deploy

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build
  only:
    - master

build_backend:
  stage: build
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/
  only:
    - master

deploy_to_app_engine:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file <(echo "$SERVICE_ACCOUNT")
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud app deploy app.yaml --stop-previous-version
  only:
    - master
